c_compiler: gcc
c_compiler_version: 11.2.0
c_stdlib: sysroot
c_stdlib_version: '2.28'
channel_targets: defaults
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cxx_compiler: gxx
extend_keys:
- pin_run_as_build
- extend_keys
- ignore_version
- ignore_build_only_deps
fortran_compiler: gfortran
ignore_build_only_deps:
- numpy
- python
lua: '5'
numpy: '1.26'
perl: 5.26.2
pin_run_as_build:
  python:
    max_pin: x.x
    min_pin: x.x
  r-base:
    max_pin: x.x
    min_pin: x.x
platform: linux-64
python: '3.12'
r_base: '3.5'
target_platform: linux-64
vc: '14'
zlib: '1.2'
